version: '3.6'

services:

  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_NAME=FoCo DS Portal
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/users_test
      - SECRET_KEY=change_me_in_prod
      - MONGO_URI=mongodb://web-mongo:27017/onehundreddaysofcode
      - MONGODB_DB=onehundreddaysofcode
      - MONGODB_HOST=web-db
      - MONGODB_PORT=27017
      - TWTR_CONSUMER_KEY=${TWTR_CONSUMER_KEY}
      - TWTR_CONSUMER_SECRET=${TWTR_CONSUMER_SECRET}
      - TWTR_TOKEN_KEY=${TWTR_TOKEN_KEY}
      - TWTR_TOKEN_SECRET=${TWTR_TOKEN_SECRET}
    depends_on:
      - web-db

  web-db:
    container_name: web-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web-mongo:
    container_name: web-mongo
    build:
      context: ./project/server/db_mongo
      dockerfile: Dockerfile
    ports:
      - 27017:27017
